import React, { useEffect } from "react";
import xmlBuilder from "xmlbuilder";

const XmlGenerator: React.FC = () => {
  useEffect(() => {
    // Sample data, replace with your actual data
    const sampleData = {
      // ... (insert your data here)
    };

    const xml = xmlBuilder.create("Document")
      .att("xmlns", "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03")
      .att("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance");

    const cstmrPmtStsRpt = xml.ele("CstmrPmtStsRpt")
      .ele("GrpHdr")
        .ele("MsgId", "BatchRef123456").up()
        .ele("CreDtTm", "2018-09-25T12:35:00").up()
        .ele("InitgPty")
          .ele("Nm", "Initiating Party Name").up()
          .ele("Id")
            .ele("OrgId")
              .ele("BICOrBEI", "SBSAZAJJXXX").up()
            .up()
          .up()
        .up()
      .up()
      .ele("OrgnlGrpInfAndSts")
        .ele("OrgnlMsgId", "OriginalMessageID").up()
        .ele("OrgnlMsgNmId", "pain.001.001.03").up()
        .ele("OrgnlCreDtTm", "2018-09-25T12:30:00").up()
        .ele("OrgnlNbOfTxs", "1").up()
        .ele("OrgnlCtrlSum", "").up()
        .ele("GrpSts", "ACSP").up()
      .up()
      .ele("OrgnlPmtInfAndSts")
        .ele("OrgnlPmtInfId", "").up()
        .ele("TxInfAndSts")
          .ele("OrgnlInstrId", "").up()
          .ele("OrgnlEndToEndId", "").up()
          .ele("TxSts", "").up()
          .ele("StsRsnInf")
            .ele("Rsn")
              .ele("Cd", "").up()
            .up()
            .ele("AddtlInf", "").up()
          .up()
          .ele("OrgnlTxRef")
            .ele("Amt")
              .ele("InstdAmt")
                .att("Ccy", "NAD")
                .text("55.00")
              .up()
            .up()
            .ele("ReqdExctnDt", "2018-09-26").up()
            .ele("PmtTpInf")
              .ele("InstrPrty", "NORM").up()
              .ele("SvcLvl")
                .ele("Cd", "").up()
                .ele("Prtry", "").up()
              .up()
            .up()
            .ele("PmtMtd", "").up()
            .ele("RmtInf")
              .ele("Ustrd", "Transaction Reference").up()
              .ele("Strd")
                .ele("CdtrRefInf")
                  .ele("Tp")
                    .ele("CdOrPrtry")
                      .ele("Prtry", "").up()
                    .up()
                  .up()
                  .ele("Ref", "").up()
                .up()
                .ele("Invcr")
                  .ele("Nm", "").up()
                  .ele("PstlAdr")
                    .ele("Dept", "").up()
                    .ele("StrtNm", "").up()
                    .ele("BldgNb", "").up()
                    .ele("PstCd", "").up()
                    .ele("TwnNm", "").up()
                    .ele("CtrySubDvsn", "").up()
                    .ele("AdrLine", "AddressLine").up()
                    .ele("AdrLine", "AddressLine").up()
                    .ele("AdrLine", "AddressLine").up()
                    .ele("AdrLine", "AddressLine").up()
                    .ele("AdrLine", "AddressLine").up()
                  .up()
                  .ele("AddtlRmtInf", "20200529/xxxx/0000/0000001/0000001").up()
                  .ele("AddtlRmtInf", "").up()
                  .ele("AddtlRmtInf", "").up()
                  .ele("AddtlRmtInf", "").up()
                  .ele("AddtlRmtInf", "").up()
                .up()
              .up()
            .up()
            .ele("Dbtr")
              .ele("Nm", "").up()
              .ele("PstlAdr")
                .ele("Ctry", "").up()
              .up()
            .up()
            .ele("DbtrAcct")
              .ele("Id")
                .ele("IBAN", "").up()
                .ele("Othr")
                  .ele("Id", "").up()
                  .ele("Tp")
                    .ele("Prtry", "").up()
                  .up()
                  .ele("Ccy", "NAD").up()
                  .ele("Nm", "").up()
                .up()
              .up()
            .up()
            .ele("DbtrAgt")
              .ele("FinInstnId")
                .ele("BIC", "").up()
                .ele("ClrSysMmbId")
                  .ele("MmbId", "").up()
                .up()
              .up()
            .up()
            .ele("CdtrAgt")
              .ele("FinInstnId")
                .ele("BIC", "").up()
                .ele("ClrSysMmbId")
                  .ele("MmbId", "").up()
                .up()
              .up()
              .ele("Nm", "").up()
            .up()
            .ele("Cdtr")
              .ele("Nm", "").up()
              .ele("PstlAdr")
                .ele("Ctry", "").up()
              .up()
              .ele("Id")
                .ele("OrgId")
                  .ele("Othr")
                    .ele("Id", "").up()
                    .ele("SchmeNm")
                      .ele("Cd", "").up()
                      .ele("Prtry", "").up()
                    .up()
                  .up()
                .up()
                .ele("PrvtId")
                  .ele("Othr")
                    .ele("Id", "").up()
                    .ele("SchmeNm")
                      .ele("Cd", "").up()
                    .up()
                  .up()
                .up()
              .up()
            .up()
            .ele("CdtrAcct")
              .ele("Id")
                .ele("IBAN", "").up()
                .ele("Othr")
                  .ele("Id", "").up()
                  .ele("SchmeNm")
                    .ele("Prtry", "").up()
                  .up()
                .up()
              .up()
              .ele("Tp")
                .ele("Cd", "").up()
                .ele("Prtry", "").up()
              .up()
              .ele("Ccy", "").up()
            .up()
          .up()
        .up()
      .up()
    .doc();

    const xmlString = xml.end({ pretty: true });
    const blob = new Blob([xmlString], { type: "text/xml" });
    const url = URL.createObjectURL(blob);

    // Create a link element and trigger a click event to download the file
    const a = document.createElement("a");
    a.href = url;
    a.download = "payment_report.xml";
    a.click();

    // Clean up by revoking the object URL
    URL.revokeObjectURL(url);
  }, []);

  return (
    <div>
      {/* Add your component JSX here */}
    </div>
  );
};

export default XmlGenerator;
